# TODO: 추후에 dev, prod로 분리

services:
  # 데이터베이스: MySQL 9.0
  db:
    image: mysql:9.0
    container_name: tripe-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d # 초기 SQL 자동 실행용
    networks:
      - tripe-network
    healthcheck:
        # mysqladmin을 사용해 DB 엔진이 실제로 응답하는지 체크합니다.
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
        interval: 5s   # 5초마다 체크
        timeout: 5s    # 5초 넘기면 실패
        retries: 10    # 10번까지 재시도
        start_period: 20s # 초기 구동 시 20초 정도는 에러로 치지 않고 기다려줌

  # 백엔드: Spring Boot 4.0
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tripe-backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev # 로컬: dev, 실환경: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_CONTAINER_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_LOCATION: ${GEMINI_LOCATION}
      GEMINI_PROJECT_ID: ${GEMINI_PROJECT_ID}
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    networks:
      - tripe-network

  # 프론트엔드: React (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tripe-frontend
    ports:
      - "${VITE_HOST_PORT}:${VITE_CONTAINER_PORT}"
    environment:
      TRIPE_API_URL: ${TRIPE_API_URL}
    networks:
      - tripe-network
    volumes:
      - ./frontend:/app

networks:
  tripe-network:
    driver: bridge

volumes:
  mysql-data: